version: '3.8'

services:
  database:
    image: postgres:14.4-alpine
    container_name: hommy_database
    restart: unless-stopped
    volumes:
      - ./node_modules/.postgresql/data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    ports:
      - '5432:5432'
